### PR TITLE
Handle Transformers API drift and CUDA Graph StaticCache state

### PR DESCRIPTION
**Pull request by EarsT913831CALS**
Hello, and thank you for providing such an excellent and timely plugin, which has made it possible to try Breeze TTS 2 in ComfyUI so quickly.

While using the project, I encountered several compatibility issues with a newer Transformers release (5.16.1). I made a few local adaptations and tested them with Transformers 4.57.3 and 5.16.1; both versions now work correctly in my environment. These findings and changes may be useful for future maintenance.

# Handle Transformers API drift and CUDA Graph StaticCache state

## Environment

- Windows / ComfyUI
- Transformers 5.16.1
- SDPA
- `eager` and `cuda_graphs` decode modes

## Issues covered

1. **P1 — Decorator:** incompatible `check_model_inputs` calling conventions.
2. **P2 — Configuration:** custom Breeze types are not registered with `AutoConfig`.
3. **P3 — Generation masks:** incompatible arguments in `native.py`.
4. **P4 — Codec masks:** the same argument incompatibility in `vendor/codec_model.py`.
5. **P5 — CUDA Graphs:** graph warm-up reuses a mutated `StaticCache`.

## Transformers version matrix

| Version | `check_model_inputs` | Mask functions | `StaticLayer.update()` | Failures in the original plugin |
| --- | --- | --- | --- | --- |
| 4.57.0–4.57.1 | Direct decorator; `@check_model_inputs()` fails | `input_embeds`; `cache_position` required | Writes to explicit `cache_position` | P1 |
| 4.57.2–4.57.3 | Decorator factory | `input_embeds`; `cache_position` required | Writes to explicit `cache_position` | None of P1/P3/P4/P5; 4.57.3 is the official baseline |
| 5.0–5.1 | Supports both forms through `func=None` | Still `input_embeds`; `cache_position` required | Writes to explicit `cache_position` | None of P1/P3/P4/P5 |
| 5.2–5.3 | Symbol absent; the existing fallback is used | Renamed to `inputs_embeds`; `cache_position` required | Writes to explicit `cache_position` | P4 |
| 5.4–5.8 | Direct decorator, deprecated; `@check_model_inputs()` fails | `inputs_embeds`; `cache_position` optional and unused, kept only for compatibility | Ignores explicit position and appends using `arange + cumulative_length` | P1, P4, and P5 in `cuda_graphs` mode |
| 5.9–5.16.1 | Direct decorator, deprecated | `inputs_embeds`; `cache_position` removed | Appends using `arange + cumulative_length` | P1, P3, P4, and P5 in `cuda_graphs` mode |

Transformers 4.57.3 and 5.16.1 were tested end to end. The intermediate boundaries above were verified from tagged Transformers source but were not all runtime-tested. P2 is a separate AutoConfig integration issue, not a confirmed Transformers version boundary; it was reproduced on 5.16.1.

### 1. `check_model_inputs()` fails during node import

The codec uses `@check_model_inputs()`. Direct-decorator releases raise:

```text
TypeError: check_model_inputs() missing 1 required positional argument: 'func'
```

The local adapter supports the factory form, direct form, and releases where the symbol is absent. This is a compatibility shim; signature inspection or migration to `merge_with_config_defaults` may be cleaner than catching `TypeError`.

### 2. Breeze config is unknown to `AutoConfig`

`AutoTokenizer.from_pretrained()` may resolve `model_type="breeze"` as a generic `PreTrainedConfig`. On 5.16.1 this later fails with:

```text
AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
```

The local adaptation registers:

```text
breeze                     -> BreezeConfig
breeze_depth_decoder_model -> BreezeDepthDecoderConfig
```

The official Breeze implementation also registers both custom config types. Registration during module initialization, or passing the already-built `model.config` directly to `AutoTokenizer`, may be cleaner than registering during every load.

### 3. Generation mask calls pass removed or renamed arguments

Both causal-mask calls in `native.py` pass `cache_position` unconditionally. Transformers 5.9+ removed it, producing:

```text
TypeError: create_causal_mask() got an unexpected keyword argument 'cache_position'
```

The embedding keyword changed from `input_embeds` to `inputs_embeds` in Transformers 5.2. `native.py` already handled that rename; its new wrapper is required from 5.9 onward to remove `cache_position`. The wrapper inspects the installed signature once and only passes supported arguments.

### 4. Codec decoding has the same incompatibility

`vendor/codec_model.py` passes one `mask_kwargs` dictionary to both:

```python
create_causal_mask(**mask_kwargs)
create_sliding_window_causal_mask(**mask_kwargs)
```

The codec still uses `input_embeds`, so it becomes incompatible in Transformers 5.2. From 5.9 onward it also passes the removed `cache_position`. Both codec mask functions now use the same signature-based normalization, with their signatures inspected separately.

The helper is currently duplicated between `native.py` and `vendor/codec_model.py`; a shared adapter would reduce maintenance of private Transformers APIs.

### 5. CUDA Graph recording starts from a mutated `StaticCache`

`_record()` executes two warm-ups before capture. Each call mutates the same cache.

Through Transformers 5.3, `StaticLayer` writes using explicit `cache_position`. Starting in 5.4, it ignores that explicit position, tracks `cumulative_length`, and derives positions as:

```python
torch.arange(kv_length) + cumulative_length
```

For the depth decoder, a previous trial leaves length 16 in a cache with valid indices `0–16`. The next two-token prefill attempts positions `[16, 17]`, causing an out-of-bounds write. This source-level behavior exists from 5.4 onward; the failure was reproduced on 5.16.1.

The local adaptation resets the cache before each warm-up and once before capture:

```text
reset -> warm-up
reset -> warm-up
reset -> capture
```

These resets are outside the recorded CUDA Graph and are not replayed during inference. A dedicated capture cache or explicit state snapshot/restore may provide stronger isolation.

## Scope

The changes restore the tested 5.16.1 path through model loading, generation, depth decoding, codec decoding, and CUDA Graph capture. They are compatibility adaptations, not confirmation that every Transformers 5.x release is fully supported.

Commits:

- https://github.com/EarsT913831CALS/ComfyUI-Breeze-TTS-2/commit/c64ee8f3180cb4b02463ee34f4d05bb2ffb30c3e
- https://github.com/EarsT913831CALS/ComfyUI-Breeze-TTS-2/commit/a11161ff13988e18f6e08dd801aa3a38ad134b53

### CODE REVIEW

**Comment by Saganaki22** [comment]
Thanks for this, the version matrix checks out (we verified the decorator forms and mask signatures against the actual wheels: 4.57.0 through 5.16.1 match your table).

We've shipped the P1 + mask fixes in v1.4.1 with a slightly different approach (unconditional no-op shim instead of calling-convention detection, and signature-filtered mask kwargs). The remaining piece here is P5 (StaticCache reset during graph capture)  that one touches the cuda_graphs path, so before merging we want numbers, not just source analysis.

Could you rebase the PR to just the P5 change on top of current main, and post benchmarks from your 5.16.1 setup:

- avg RTF (eager vs cuda_graphs, before and after the reset change)
- peak VRAM for both modes
- a quick Whisper WER check against the prompt text to confirm the resets don't alter output

The methodology we use is in the README benchmarks table (RTX 5090, sdpa). If the resets are truly outside the captured graph, RTF should be unchanged vs current main on 5.3  but we'd rather see it measured than argued.

**Comment by EarsT913831CALS** [comment]
## Benchmark results

I tested the P5 `StaticCache` reset change with Transformers 5.3.0 and 5.16.1.

### Test environment

- OS: Windows
- Application: ComfyUI
- GPU: NVIDIA GeForce RTX 5070 Ti
- Transformers: 5.3.0 and 5.16.1
- Decode modes: `eager` and `cuda_graphs`
- Audio format: FLAC
- VRAM monitoring: `nvidia-smi`, sampled every 100 ms
- WER evaluator: `openai/whisper-large-v3-turbo`
- Warm-up: one run with `seed=42`
- Measured runs: three runs with `seeds=43,44,45`

The prompt, workflow, model settings, and seed sequence were identical across comparisons. RTF was calculated separately for each output and then averaged.

| Transformers | Code | Decode mode | Mean RTF | Peak VRAM | WER | Result |
|---|---|---|---:|---:|---:|---|
| 5.16.1 | `upstream/main + P2` | eager | 2.070 | 11,811 MiB | 0.00% | Pass |
| 5.16.1 | `upstream/main + P2` | cuda_graphs | N/A | N/A | N/A | CUDA Graph capture failed |
| 5.16.1 | `upstream/main + P2 + P5` | eager | 2.104 | 11,422 MiB | 0.00% | Pass |
| 5.16.1 | `upstream/main + P2 + P5` | cuda_graphs | 0.822 | 13,484 MiB | 0.00% | Pass |
| 5.3.0 | `upstream/main` | eager | 2.013 | 11,905 MiB | 0.00% | Pass |
| 5.3.0 | `upstream/main` | cuda_graphs | 0.799 | 13,956 MiB | 0.00% | Pass |
| 5.3.0 | `upstream/main + P5` | eager | 2.002 | 11,892 MiB | 0.00% | Pass |
| 5.3.0 | `upstream/main + P5` | cuda_graphs | 0.800 | 13,802 MiB | 0.00% | Pass |

The three measured audio durations were identical across every successful group: 18.40 s, 13.60 s, and 14.64 s.

### Findings

- With Transformers 5.16.1, the P2-only baseline still failed during CUDA Graph capture. Adding P5 allowed the same configuration to complete successfully.
- With P5, CUDA Graph mode reached a mean RTF of `0.822`, compared with `2.104` in eager mode—approximately `2.56x` faster.
- On Transformers 5.3.0, P5 changed mean RTF by approximately `-0.56%` in eager mode and `+0.21%` in CUDA Graph mode. With three measured runs, these are small observational differences rather than evidence of a performance regression.
- P5 did not increase the observed peak VRAM on Transformers 5.3.0.
- All 21 successfully generated measured outputs produced `0.00%` WER, so I did not observe an output-quality regression.

Peak VRAM is the maximum total GPU `memory.used` value sampled with `nvidia-smi`; it includes model loading and CUDA Graph capture.

### Transformers 5.16.1 compatibility note

One additional blocker remains in current `upstream/main`: P2 is still reproducible with Transformers 5.16.1. Without registering the custom Breeze config types, model loading stops before the CUDA Graph path can be tested.

For the P5 benchmarks, I applied the same local P2-only compatibility shim to both branches:

- Baseline: `upstream/main + P2`
- Patched: `upstream/main + P2 + P5`

Therefore, P5 was the only code difference between the two 5.16.1 benchmark groups.

~~P2 was kept as a local, test-only commit and is not part of this PR.~~

**Update:** P2 has now been restored to this PR as a separate commit after the issue was independently reproduced on Transformers 5.16.1.

The complete failure path is:

1. The loader initially constructs the model manually with `native.BreezeConfig`, so the missing registration is not encountered during the initial model construction.
2. `AutoTokenizer.from_pretrained()` later calls `AutoConfig.from_pretrained()` internally.
3. Because the checkpoint declares `model_type: "breeze"` but that type is not registered in Transformers' `CONFIG_MAPPING`, the lookup fails with `KeyError: 'breeze'`.
4. `AutoTokenizer` falls back to the generic `PreTrainedConfig`.
5. In Transformers 5.16.1, the generic config performs RoPE parameter standardization before the remaining checkpoint fields have been assigned to the object. It therefore accesses `self.max_position_embeddings` too early and raises:

   ```text
   AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
   ```

`max_position_embeddings` is present in `config.json`; the error occurs because Transformers selected the generic configuration class and attempted to read the field before assigning it.

This also explains why the same unregistered fallback works with Transformers 5.3.0: that version does not trigger the same early RoPE-standardization path.

The registrations for both `breeze` and `breeze_depth_decoder_model` have therefore been restored with `exist_ok=True`, consistent with the [[official Breeze implementation](https://github.com/breezeblue-ai/breeze-tts/blob/main/models/breeze_config.py)](https://github.com/breezeblue-ai/breeze-tts/blob/main/models/breeze_config.py).

P2 remains separate from P5 in the commit history: P2 fixes tokenizer/config loading, while P5 fixes the later CUDA Graph capture failure. This update does not change the validity of the P5 benchmarks because the same P2 code was applied to both 5.16.1 benchmark branches.

**Comment by EarsT913831CALS** [comment]
And this is my raw result：
[results.zip](https://github.com/user-attachments/files/31608138/results.zip)

**Comment by thr12345** [comment]
Thanks for putting this PR together! I was getting errors before seeing you post this.
I tested it with Transformers 5.16.1 and can confirm that the `AutoConfig` registration fix is needed.

Without it, the model loader fails in `AutoTokenizer.from_pretrained()` with:

```text
AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
```

The log also shows `KeyError: 'breeze'`, so Transformers isn’t recognizing the custom Breeze configuration.

It looks like the PR’s current branch only contains the `StaticCache` reset change. When I switched to commit `a11161ff13988e18f6e08dd801aa3a38ad134b53`, which still includes the registration changes from `c64ee8f3180cb4b02463ee34f4d05bb2ffb30c3e`, the model and codec loaded successfully and generation worked.

Would you mind restoring the `AutoConfig` registrations for both `breeze` and `breeze_depth_decoder_model`? Thanks again!

**Comment by EarsT913831CALS** [comment]
> Thanks for putting this PR together! I was getting errors before seeing you post this. I tested it with Transformers 5.16.1 and can confirm that the `AutoConfig` registration fix is needed.
> 
> Without it, the model loader fails in `AutoTokenizer.from_pretrained()` with:
> 
> ```
> AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
> ```
> 
> The log also shows `KeyError: 'breeze'`, so Transformers isn’t recognizing the custom Breeze configuration.
> 
> It looks like the PR’s current branch only contains the `StaticCache` reset change. When I switched to commit `a11161ff13988e18f6e08dd801aa3a38ad134b53`, which still includes the registration changes from `c64ee8f3180cb4b02463ee34f4d05bb2ffb30c3e`, the model and codec loaded successfully and generation worked.
> 
> Would you mind restoring the `AutoConfig` registrations for both `breeze` and `breeze_depth_decoder_model`? Thanks again!

@thr12345 
I have restored both registrations.
I have also further investigated P2 and found the actual reason:

> Therefore, P5 was the only code difference between the two 5.16.1 benchmark groups.
> 
> ~P2 was kept as a local, test-only commit and is not part of this PR.~
> 
> **Update:** P2 has now been restored to this PR as a separate commit after the issue was independently reproduced on Transformers 5.16.1.
> 
> The complete failure path is:
> 
> 1. The loader initially constructs the model manually with `native.BreezeConfig`, so the missing registration is not encountered during the initial model construction.
> 2. `AutoTokenizer.from_pretrained()` later calls `AutoConfig.from_pretrained()` internally.
> 3. Because the checkpoint declares `model_type: "breeze"` but that type is not registered in Transformers' `CONFIG_MAPPING`, the lookup fails with `KeyError: 'breeze'`.
> 4. `AutoTokenizer` falls back to the generic `PreTrainedConfig`.
> 5. In Transformers 5.16.1, the generic config performs RoPE parameter standardization before the remaining checkpoint fields have been assigned to the object. It therefore accesses `self.max_position_embeddings` too early and raises:
>    ```
>    AttributeError: 'PreTrainedConfig' object has no attribute 'max_position_embeddings'
>    ```
> 
> `max_position_embeddings` is present in `config.json`; the error occurs because Transformers selected the generic configuration class and attempted to read the field before assigning it.
> 
> This also explains why the same unregistered fallback works with Transformers 5.3.0: that version does not trigger the same early RoPE-standardization path.
> 
> The registrations for both `breeze` and `breeze_depth_decoder_model` have therefore been restored with `exist_ok=True`, consistent with the [[official Breeze implementation](https://github.com/breezeblue-ai/breeze-tts/blob/main/models/breeze_config.py)](https://github.com/breezeblue-ai/breeze-tts/blob/main/models/breeze_config.py).
> 
> P2 remains separate from P5 in the commit history: P2 fixes tokenizer/config loading, while P5 fixes the later CUDA Graph capture failure. This update does not change the validity of the P5 benchmarks because the same P2 code was applied to both 5.16.1 benchmark branches.

**Comment by Saganaki22** [comment]
The P2 traceback matched the 5.16.1 source line-for-line on our side too, and the benchmarks held up: we re-ran capture + replay on 5.3.0 (RTX 5090) after merging, no issues.

One small change on top: we moved the AutoConfig registration from `load_breeze_bundle` to module init in `native.py`  Everything shipped in v1.4.2 with you credited in the release notes.

Thanks @thr12345 for the independent reproduction as well.
